### ISSUE TITLE
Error executing action `create` on resource 'openstack_project[service]'

### ISSUE THREAD

**Issue by smekalayahoo** [cloudbau/cookbook-openstackclient#6]
Excon::Error::Timeout
---------------------
read timeout reached

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/openstackclient/libraries/openstack_project.rb:28:in `find'
/var/chef/cache/cookbooks/openstackclient/libraries/openstack_project.rb:28:in `block in <class:OpenstackProject>'

We are seeing this issue too frequently in our builds. Is there a way to increase the default timeout value?

We are using "version": "15.0.1" of this cookbook

**Comment by jklare** [comment]
Hi,

we are doing regular deployment and also integration builds with this cookbook resource and have never run into timeout issues iirc. Can you specify in which setup you see this?

Cheers,
Jan

**Comment by jklare** [comment]
Hi,

i will close this issue due to inactivity. Please feel free to open this again if you run into the problem you descibed above.

Cheers,
Jan
